# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-23 16:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import project_name.apps.core.utils.upload_folder
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('dateCreated', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('dateModified', models.DateTimeField(auto_now=True, null=True, verbose_name='date modified')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('isDeleted', models.BooleanField(default=False, editable=False)),
                ('userId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='userprofile_userprofile_userId', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='address')),
                ('genderTypeId', models.CharField(blank=True, choices=[('01', 'MALE'), ('02', 'FEMALE')], max_length=10, null=True, verbose_name='gender')),
                ('documentIdentityTypeId', models.CharField(blank=True, choices=[('01', 'DNI'), ('02', 'RUC'), ('03', 'PASSPORT')], max_length=10, null=True, verbose_name='document identity')),
                ('documentIdentityNumber', models.CharField(blank=True, max_length=50, null=True, verbose_name='document number')),
                ('homePhone', models.CharField(blank=True, max_length=50, null=True, verbose_name='home phone')),
                ('mobilePhone', models.CharField(blank=True, max_length=50, null=True, verbose_name='mobile phone')),
                ('logoProfile', models.ImageField(blank=True, null=True, upload_to=project_name.apps.core.utils.upload_folder.upload_user_profile, verbose_name='logo')),
            ],
            options={
                'verbose_name': '01. Profile',
                'verbose_name_plural': '01. Profiles',
                'db_table': 'userProfile',
            },
            managers=[
                ('current', django.db.models.manager.Manager()),
            ],
        ),
    ]
