# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-23 14:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreated', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('dateModified', models.DateTimeField(auto_now=True, null=True, verbose_name='date modified')),
                ('isDeleted', models.BooleanField(default=False, editable=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='name')),
                ('icon', models.CharField(blank=True, max_length=200, null=True, verbose_name='icon')),
                ('match', models.CharField(default='#', max_length=200, verbose_name='match')),
                ('urlName', models.CharField(blank=True, max_length=200, null=True, verbose_name='urlName')),
                ('reference', models.CharField(max_length=100, unique=True, verbose_name='reference')),
                ('order', models.IntegerField(default=0, verbose_name='order')),
                ('bandType', models.CharField(choices=[('BAND-1', 'Band 1'), ('BAND-2', 'Band 2'), ('BAND-3', 'Band 3'), ('BAND-4', 'Band 4'), ('BAND-5', 'Band 5'), ('BAND-6', 'Band 6'), ('BAND-7', 'Band 7'), ('BAND-8', 'Band 8')], default='BAND-1', max_length=80, verbose_name='band type')),
            ],
            options={
                'verbose_name': '01. module',
                'verbose_name_plural': '01. modules',
                'ordering': ['order'],
            },
            managers=[
                ('current', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ModuleItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreated', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('dateModified', models.DateTimeField(auto_now=True, null=True, verbose_name='date modified')),
                ('isDeleted', models.BooleanField(default=False, editable=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='name')),
                ('icon', models.CharField(blank=True, max_length=200, null=True, verbose_name='icon')),
                ('match', models.CharField(default='#', max_length=200, verbose_name='match')),
                ('urlName', models.CharField(blank=True, max_length=200, null=True, verbose_name='urlName')),
                ('reference', models.CharField(max_length=100, unique=True, verbose_name='reference')),
                ('order', models.IntegerField(default=0, verbose_name='order')),
                ('moduleId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_moduleitem_moduleId', to='module.Module', verbose_name='module')),
            ],
            options={
                'verbose_name': '02. module item',
                'verbose_name_plural': '02. module items',
                'ordering': ['moduleId'],
            },
            managers=[
                ('current', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='RoleModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreated', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('dateModified', models.DateTimeField(auto_now=True, null=True, verbose_name='date modified')),
                ('isDeleted', models.BooleanField(default=False, editable=False)),
                ('moduleId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='module_rolemodule_moduleId', to='module.Module', verbose_name='module')),
                ('roleId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='module_rolemodule_roleId', to='core.Role', verbose_name='role')),
            ],
            options={
                'verbose_name': '03. module team',
                'verbose_name_plural': '03. module teams',
            },
            managers=[
                ('current', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='RoleModuleItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreated', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('dateModified', models.DateTimeField(auto_now=True, null=True, verbose_name='date modified')),
                ('isDeleted', models.BooleanField(default=False, editable=False)),
                ('moduleItemId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_rolemoduleitem_moduleItemId', to='module.ModuleItem', verbose_name='module item')),
                ('roleModuleId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_rolemoduleitem_roleModuleId', to='module.RoleModule', verbose_name='role module')),
            ],
            options={
                'verbose_name': '04. module item team',
                'verbose_name_plural': '04. module item teams',
            },
            managers=[
                ('current', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='module',
            unique_together=set([('name',)]),
        ),
        migrations.AlterUniqueTogether(
            name='rolemoduleitem',
            unique_together=set([('roleModuleId', 'moduleItemId')]),
        ),
        migrations.AlterUniqueTogether(
            name='rolemodule',
            unique_together=set([('roleId', 'moduleId')]),
        ),
    ]
