# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-23 14:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import project_name.apps.core.manager
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreated', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('dateModified', models.DateTimeField(auto_now=True, null=True, verbose_name='date modified')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('isDeleted', models.BooleanField(default=False, editable=False)),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='name')),
            ],
            options={
                'verbose_name': '01. group',
                'verbose_name_plural': '01. groups',
            },
            managers=[
                ('objects', project_name.apps.core.manager.TeamManager()),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreated', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('dateModified', models.DateTimeField(auto_now=True, null=True, verbose_name='date modified')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('isDeleted', models.BooleanField(default=False, editable=False)),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='name')),
                ('codename', models.CharField(max_length=80, unique=True, verbose_name='codename')),
            ],
            options={
                'verbose_name': '03. permission',
                'verbose_name_plural': '03. permissions',
            },
            managers=[
                ('objects', project_name.apps.core.manager.PermissionManager()),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreated', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('dateModified', models.DateTimeField(auto_now=True, null=True, verbose_name='date modified')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('isDeleted', models.BooleanField(default=False, editable=False)),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='name')),
                ('codename', models.CharField(max_length=80, unique=True, verbose_name='codename')),
                ('groupId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_role_groupId', to='core.Group', verbose_name='team')),
            ],
            options={
                'verbose_name': '02. role',
                'verbose_name_plural': '02. roles',
            },
            managers=[
                ('current', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreated', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('dateModified', models.DateTimeField(auto_now=True, null=True, verbose_name='date modified')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('isDeleted', models.BooleanField(default=False, editable=False)),
                ('type', models.CharField(choices=[('01', 'CURRENCY TYPE'), ('02', 'USER TYPE'), ('03', 'ROLE TEAM TYPE'), ('04', 'COLUMN ROLE TYPE'), ('05', 'COLUMN VALUE TYPE'), ('06', 'PROJECT TYPE'), ('07', 'STATUS TYPE'), ('08', 'PAYMENT TYPE'), ('09', 'DOCUMENT IDENTITY TYPE'), ('10', 'DOCUMENT COMPANY_TYPE'), ('11', 'UPLOAD DATASET TYPE'), ('12', 'GENDER TYPE'), ('13', 'TRANSACTION TYPE'), ('17', 'SPACEPLAN TYPE'), ('14', 'STATU CIVIL TYPE'), ('15', 'DATASET TYPE'), ('16', 'COIN TYPE'), ('18', 'STATUS USER'), ('19', 'STATUS PROJECT'), ('20', 'STATUS DATASET'), ('21', 'STATUS TEAM'), ('22', 'STATUS TRANSACTION'), ('23', 'STATUS AFFILIATE'), ('24', 'STATUS COMPANY'), ('25', 'STATUS SOLUTION')], max_length=10, verbose_name='type')),
                ('code', models.CharField(max_length=20, verbose_name='code')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
            ],
            options={
                'verbose_name': '04. Type',
                'verbose_name_plural': '04. Types',
            },
            managers=[
                ('current', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='types',
            unique_together=set([('type', 'code')]),
        ),
        migrations.AlterUniqueTogether(
            name='permission',
            unique_together=set([('name',)]),
        ),
        migrations.AlterUniqueTogether(
            name='group',
            unique_together=set([('name',)]),
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together=set([('groupId', 'name', 'codename')]),
        ),
    ]
