# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-23 14:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import project_name.apps.core.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('firstName', models.CharField(blank=True, max_length=40, null=True, verbose_name='first name')),
                ('lastName', models.CharField(blank=True, max_length=40, null=True, verbose_name='last name')),
                ('displayName', models.CharField(blank=True, max_length=14, null=True, verbose_name='display name')),
                ('isActive', models.BooleanField(default=True, verbose_name='is_active')),
                ('isAdmin', models.BooleanField(default=False, verbose_name='is_admin ')),
                ('groupId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_user_groupId', to='core.Group', verbose_name='group')),
                ('roleId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_user_roleId', to='core.Role', verbose_name='role')),
            ],
            options={
                'verbose_name': '01. user',
                'verbose_name_plural': '01. users',
                'db_table': 'user',
                'abstract': False,
                'swappable': 'user.User',
            },
            managers=[
                ('objects', project_name.apps.core.manager.UserManager()),
            ],
        ),
    ]
