from django.utils.translation import ugettext_lazy as _

CODE_TEXT_EDIT = 'EDIT'
TEXT_MSG_SUCCESS = _('Data saved correctly')
TEXT_MSG_ERROR = _('There was an error saving information')
TEXT_MSG_WARNING = _('It required to complete required fields')
STATUS_MSG_TAGS = {
    'success': TEXT_MSG_SUCCESS,
    'error': TEXT_MSG_ERROR,
    'warning': TEXT_MSG_WARNING,
}

NAME_SELECT_DEFAULT = _('--Choose--')
SELECT_DEFAULT_LIST = [('', NAME_SELECT_DEFAULT)]
SELECT_DEFAULT_TUPLE = (('', NAME_SELECT_DEFAULT),)
DISABLED = 'DISABLED'
ENABLED = 'ENABLED'
STATUS_MODEL = (
    (ENABLED, _('Enabled')),
    (DISABLED, _('Disabled')),
)

# ITEMS BAND TYPE MENU
CODE_BAND_ONE = 'BAND-1'
CODE_BAND_TWO = 'BAND-2'
CODE_BAND_THREE = 'BAND-3'
CODE_BAND_FOUR = 'BAND-4'
CODE_BAND_FIVE = 'BAND-5'
CODE_BAND_SIX = 'BAND-6'

CODE_BAND_SEVEN = 'BAND-7'
CODE_BAND_EIGHT = 'BAND-8'

BAND_ONE_STRING = (CODE_BAND_ONE, _('Band 1'))
BAND_TWO_STRING = (CODE_BAND_TWO, _('Band 2'))
BAND_THREE_STRING = (CODE_BAND_THREE, _('Band 3'))
BAND_FOUR_STRING = (CODE_BAND_FOUR, _('Band 4'))
BAND_FIVE_STRING = (CODE_BAND_FIVE, _('Band 5'))
BAND_SIX_STRING = (CODE_BAND_SIX, _('Band 6'))
BAND_SEVEN_STRING = (CODE_BAND_SEVEN, _('Band 7'))
BAND_EIGHT_STRING = (CODE_BAND_EIGHT, _('Band 8'))

TYPE_BAND_OPTIONS = (
    BAND_ONE_STRING, BAND_TWO_STRING, BAND_THREE_STRING,
    BAND_FOUR_STRING, BAND_FIVE_STRING, BAND_SIX_STRING,
    BAND_SEVEN_STRING, BAND_EIGHT_STRING
)

SIS_USER_TYPE = 0
CODE_USER_ACTIVE = "01"
CODE_USER_INACTIVE = "02"

SIS_DOCUMENT_IDENTITY_TYPE = 1
CODE_DOCUMENT_DNI = '01'
CODE_DOCUMENT_RUC = '02'
CODE_DOCUMENT_PASSPORT = '03'

SIS_TRIBUTE_PERSON_TYPE = 2
CODE_TRIBUTE_PERSON_NATURAL = '01'
CODE_TRIBUTE_PERSON_JURIDICAL = '02'

SIS_GENDER_TYPE = 3
CODE_GENDER_MALE = '01'
CODE_GENDER_FEMALE = '02'

SIS_CIVIL_TYPE = 4
CODE_CIVIL_STATUS_SINGLE = '01'
CODE_CIVIL_STATUS_MARRIED = '02'
CODE_CIVIL_STATUS_WIDOWED = '03'
CODE_CIVIL_STATUS_DIVORCED = '04'
CODE_CIVIL_STATUS_SEPARATED = '05'

TYPE_OPTIONS = (
    (SIS_USER_TYPE,
     (
         (CODE_USER_ACTIVE, _('ACTIVE')),
         (CODE_USER_INACTIVE, _('INACTIVE'))
     )
     ),
    (SIS_DOCUMENT_IDENTITY_TYPE,
     (
         (CODE_DOCUMENT_DNI, _('DNI')),
         (CODE_DOCUMENT_RUC, _('RUC')),
         (CODE_DOCUMENT_PASSPORT, _('PASSPORT'))
     )
     ),
    (SIS_TRIBUTE_PERSON_TYPE,
     (
         (CODE_TRIBUTE_PERSON_NATURAL, _('NATURAL')),
         (CODE_TRIBUTE_PERSON_JURIDICAL, _('JURIDICAL'))
     )
     ),
    (SIS_GENDER_TYPE,
     (
         (CODE_GENDER_MALE, _('MALE')),
         (CODE_GENDER_FEMALE, _('FEMALE'))
     )
     ),
)

